// Code generated by artifact/protogen from schema/codiq.graphql. DO NOT EDIT.
//
// One file's extracted facts (SPEC.md §5): the map phase's output, written to
// the shared volume (§10) and read back by the reduce (§6). The message shapes
// are the SDL's vertex tables; the identity model is the extractor's, so a row
// is named by a file-local ordinal rather than by the uuid the store assigns.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: codiq/facts/v1/facts.proto

package factsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VertexKind names one of the SDL's vertex tables: which table an edge
// endpoint is a row in.
type VertexKind int32

const (
	VertexKind_VERTEX_KIND_UNSPECIFIED VertexKind = 0
	VertexKind_VERTEX_KIND_FILE        VertexKind = 1
	VertexKind_VERTEX_KIND_SCOPE       VertexKind = 2
	VertexKind_VERTEX_KIND_OCCURRENCE  VertexKind = 3
)

// Enum value maps for VertexKind.
var (
	VertexKind_name = map[int32]string{
		0: "VERTEX_KIND_UNSPECIFIED",
		1: "VERTEX_KIND_FILE",
		2: "VERTEX_KIND_SCOPE",
		3: "VERTEX_KIND_OCCURRENCE",
	}
	VertexKind_value = map[string]int32{
		"VERTEX_KIND_UNSPECIFIED": 0,
		"VERTEX_KIND_FILE":        1,
		"VERTEX_KIND_SCOPE":       2,
		"VERTEX_KIND_OCCURRENCE":  3,
	}
)

func (x VertexKind) Enum() *VertexKind {
	p := new(VertexKind)
	*p = x
	return p
}

func (x VertexKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VertexKind) Descriptor() protoreflect.EnumDescriptor {
	return file_codiq_facts_v1_facts_proto_enumTypes[0].Descriptor()
}

func (VertexKind) Type() protoreflect.EnumType {
	return &file_codiq_facts_v1_facts_proto_enumTypes[0]
}

func (x VertexKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VertexKind.Descriptor instead.
func (VertexKind) EnumDescriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{0}
}

// EdgeKind names an extracted, intra-file edge — SPEC.md §4.4's base edge
// tables. The derived cross-file kinds are the link pass's (§7) and never
// appear in an artifact.
type EdgeKind int32

const (
	EdgeKind_EDGE_KIND_UNSPECIFIED      EdgeKind = 0
	EdgeKind_EDGE_KIND_DEFINES          EdgeKind = 1
	EdgeKind_EDGE_KIND_CONTAINS         EdgeKind = 2
	EdgeKind_EDGE_KIND_REFERENCES_LOCAL EdgeKind = 3
)

// Enum value maps for EdgeKind.
var (
	EdgeKind_name = map[int32]string{
		0: "EDGE_KIND_UNSPECIFIED",
		1: "EDGE_KIND_DEFINES",
		2: "EDGE_KIND_CONTAINS",
		3: "EDGE_KIND_REFERENCES_LOCAL",
	}
	EdgeKind_value = map[string]int32{
		"EDGE_KIND_UNSPECIFIED":      0,
		"EDGE_KIND_DEFINES":          1,
		"EDGE_KIND_CONTAINS":         2,
		"EDGE_KIND_REFERENCES_LOCAL": 3,
	}
)

func (x EdgeKind) Enum() *EdgeKind {
	p := new(EdgeKind)
	*p = x
	return p
}

func (x EdgeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_codiq_facts_v1_facts_proto_enumTypes[1].Descriptor()
}

func (EdgeKind) Type() protoreflect.EnumType {
	return &file_codiq_facts_v1_facts_proto_enumTypes[1]
}

func (x EdgeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeKind.Descriptor instead.
func (EdgeKind) EnumDescriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{1}
}

// Coord is a package coordinate: the descriptor prefix (SPEC.md §4.3) the
// batch resolves from a manifest and hands to every stanza. Its four
// components are the `file` row's pkg_* columns.
//
// coord.Coord's Root is deliberately absent. Root is extraction-time
// resolution state — it is what Coord.Namespace resolves a file path
// against — and by the time an artifact exists every namespace has already
// been resolved into a descriptor suffix. The descriptor prefix is exactly
// the four components below.
type Coord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Scheme        string                 `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Manager       string                 `protobuf:"bytes,2,opt,name=manager,proto3" json:"manager,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Coord) Reset() {
	*x = Coord{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{0}
}

func (x *Coord) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Coord) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *Coord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Coord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Descriptor is a symbol's SCIP-style name (SPEC.md §4.3) as an artifact
// carries it: the two halves that produce it, not the joined string the
// `occurrence.descriptor` column holds. The split is §4.3's ownership
// boundary — prefix is the batch's, suffix is the stanza's — and an artifact
// is written before anything joins them.
type Descriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prefix        *Coord                 `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix        string                 `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{1}
}

func (x *Descriptor) GetPrefix() *Coord {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *Descriptor) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

// Ref is an edge endpoint: which vertex table, and which row in it.
// `contains` is one label over two physical tables, so the endpoint's table
// is carried rather than inferred from the kind.
type Ref struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vertex        VertexKind             `protobuf:"varint,1,opt,name=vertex,proto3,enum=codiq.facts.v1.VertexKind" json:"vertex,omitempty"`
	LocalId       int32                  `protobuf:"varint,2,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ref) Reset() {
	*x = Ref{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{2}
}

func (x *Ref) GetVertex() VertexKind {
	if x != nil {
		return x.Vertex
	}
	return VertexKind_VERTEX_KIND_UNSPECIFIED
}

func (x *Ref) GetLocalId() int32 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

// Edge is a row in one of the extracted edge tables. Both endpoints are in
// this file, always: an edge that leaves the file is the link pass's.
type Edge struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          EdgeKind               `protobuf:"varint,1,opt,name=kind,proto3,enum=codiq.facts.v1.EdgeKind" json:"kind,omitempty"`
	Source        *Ref                   `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target        *Ref                   `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Edge) Reset() {
	*x = Edge{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{3}
}

func (x *Edge) GetKind() EdgeKind {
	if x != nil {
		return x.Kind
	}
	return EdgeKind_EDGE_KIND_UNSPECIFIED
}

func (x *Edge) GetSource() *Ref {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Edge) GetTarget() *Ref {
	if x != nil {
		return x.Target
	}
	return nil
}

// File is a row in `file`, as the extractor produces it.
type File struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Path  string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Lang  string                 `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	// The pkg_* columns, as the coordinate they are.
	Coord         *Coord `protobuf:"bytes,3,opt,name=coord,proto3" json:"coord,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *File) GetCoord() *Coord {
	if x != nil {
		return x.Coord
	}
	return nil
}

// Scope is a row in `scope`, as the extractor produces it.
type Scope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity inside this artifact: a facts.LocalID, not the uuid
	// the store assigns at insert. Numbered from 1; 0 means none.
	LocalId    int32  `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	Kind       string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	RangeStart int32  `protobuf:"varint,3,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd   int32  `protobuf:"varint,4,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// An intra-file reference to another row's local_id; 0 means none.
	ParentScopeId int32 `protobuf:"varint,5,opt,name=parent_scope_id,json=parentScopeId,proto3" json:"parent_scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Scope) Reset() {
	*x = Scope{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{5}
}

func (x *Scope) GetLocalId() int32 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Scope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Scope) GetRangeStart() int32 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *Scope) GetRangeEnd() int32 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

func (x *Scope) GetParentScopeId() int32 {
	if x != nil {
		return x.ParentScopeId
	}
	return 0
}

// Occurrence is a row in `occurrence`, as the extractor produces it.
type Occurrence struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity inside this artifact: a facts.LocalID, not the uuid
	// the store assigns at insert. Numbered from 1; 0 means none.
	LocalId     int32       `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	Descriptor_ *Descriptor `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Role        string      `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	SymbolKind  string      `protobuf:"bytes,4,opt,name=symbol_kind,json=symbolKind,proto3" json:"symbol_kind,omitempty"`
	Name        string      `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	RangeStart  int32       `protobuf:"varint,6,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd    int32       `protobuf:"varint,7,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// An intra-file reference to another row's local_id; 0 means none.
	ScopeId       int32 `protobuf:"varint,8,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Occurrence) Reset() {
	*x = Occurrence{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Occurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Occurrence) ProtoMessage() {}

func (x *Occurrence) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Occurrence.ProtoReflect.Descriptor instead.
func (*Occurrence) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{6}
}

func (x *Occurrence) GetLocalId() int32 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Occurrence) GetDescriptor_() *Descriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Occurrence) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Occurrence) GetSymbolKind() string {
	if x != nil {
		return x.SymbolKind
	}
	return ""
}

func (x *Occurrence) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Occurrence) GetRangeStart() int32 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *Occurrence) GetRangeEnd() int32 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

func (x *Occurrence) GetScopeId() int32 {
	if x != nil {
		return x.ScopeId
	}
	return 0
}

// FileFacts is everything extraction knows about one file: the unit the map
// phase writes to the shared volume and the reduce phase loads (SPEC.md §5,
// §6). It is wholly self-contained — nothing in it refers to another file.
type FileFacts struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	File        *File                  `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Scopes      []*Scope               `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Occurrences []*Occurrence          `protobuf:"bytes,3,rep,name=occurrences,proto3" json:"occurrences,omitempty"`
	Edges       []*Edge                `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	// Non-empty when the file could not be parsed (SPEC.md §5's poison file).
	// The Parser contract returns no error, so the failure travels with the
	// facts: the row lists are empty and the caller decides what to do.
	ParseError    string `protobuf:"bytes,5,opt,name=parse_error,json=parseError,proto3" json:"parse_error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileFacts) Reset() {
	*x = FileFacts{}
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileFacts) ProtoMessage() {}

func (x *FileFacts) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileFacts.ProtoReflect.Descriptor instead.
func (*FileFacts) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{7}
}

func (x *FileFacts) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileFacts) GetScopes() []*Scope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *FileFacts) GetOccurrences() []*Occurrence {
	if x != nil {
		return x.Occurrences
	}
	return nil
}

func (x *FileFacts) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *FileFacts) GetParseError() string {
	if x != nil {
		return x.ParseError
	}
	return ""
}

var File_codiq_facts_v1_facts_proto protoreflect.FileDescriptor

const file_codiq_facts_v1_facts_proto_rawDesc = "" +
	"\n" +
	"\x1acodiq/facts/v1/facts.proto\x12\x0ecodiq.facts.v1\"g\n" +
	"\x05Coord\x12\x16\n" +
	"\x06scheme\x18\x01 \x01(\tR\x06scheme\x12\x18\n" +
	"\amanager\x18\x02 \x01(\tR\amanager\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\"S\n" +
	"\n" +
	"Descriptor\x12-\n" +
	"\x06prefix\x18\x01 \x01(\v2\x15.codiq.facts.v1.CoordR\x06prefix\x12\x16\n" +
	"\x06suffix\x18\x02 \x01(\tR\x06suffix\"T\n" +
	"\x03Ref\x122\n" +
	"\x06vertex\x18\x01 \x01(\x0e2\x1a.codiq.facts.v1.VertexKindR\x06vertex\x12\x19\n" +
	"\blocal_id\x18\x02 \x01(\x05R\alocalId\"\x8e\x01\n" +
	"\x04Edge\x12,\n" +
	"\x04kind\x18\x01 \x01(\x0e2\x18.codiq.facts.v1.EdgeKindR\x04kind\x12+\n" +
	"\x06source\x18\x02 \x01(\v2\x13.codiq.facts.v1.RefR\x06source\x12+\n" +
	"\x06target\x18\x03 \x01(\v2\x13.codiq.facts.v1.RefR\x06target\"[\n" +
	"\x04File\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x12\n" +
	"\x04lang\x18\x02 \x01(\tR\x04lang\x12+\n" +
	"\x05coord\x18\x03 \x01(\v2\x15.codiq.facts.v1.CoordR\x05coord\"\x9c\x01\n" +
	"\x05Scope\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\x05R\alocalId\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12\x1f\n" +
	"\vrange_start\x18\x03 \x01(\x05R\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\x04 \x01(\x05R\brangeEnd\x12&\n" +
	"\x0fparent_scope_id\x18\x05 \x01(\x05R\rparentScopeId\"\x85\x02\n" +
	"\n" +
	"Occurrence\x12\x19\n" +
	"\blocal_id\x18\x01 \x01(\x05R\alocalId\x12:\n" +
	"\n" +
	"descriptor\x18\x02 \x01(\v2\x1a.codiq.facts.v1.DescriptorR\n" +
	"descriptor\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x1f\n" +
	"\vsymbol_kind\x18\x04 \x01(\tR\n" +
	"symbolKind\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1f\n" +
	"\vrange_start\x18\x06 \x01(\x05R\n" +
	"rangeStart\x12\x1b\n" +
	"\trange_end\x18\a \x01(\x05R\brangeEnd\x12\x19\n" +
	"\bscope_id\x18\b \x01(\x05R\ascopeId\"\xef\x01\n" +
	"\tFileFacts\x12(\n" +
	"\x04file\x18\x01 \x01(\v2\x14.codiq.facts.v1.FileR\x04file\x12-\n" +
	"\x06scopes\x18\x02 \x03(\v2\x15.codiq.facts.v1.ScopeR\x06scopes\x12<\n" +
	"\voccurrences\x18\x03 \x03(\v2\x1a.codiq.facts.v1.OccurrenceR\voccurrences\x12*\n" +
	"\x05edges\x18\x04 \x03(\v2\x14.codiq.facts.v1.EdgeR\x05edges\x12\x1f\n" +
	"\vparse_error\x18\x05 \x01(\tR\n" +
	"parseError*r\n" +
	"\n" +
	"VertexKind\x12\x1b\n" +
	"\x17VERTEX_KIND_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VERTEX_KIND_FILE\x10\x01\x12\x15\n" +
	"\x11VERTEX_KIND_SCOPE\x10\x02\x12\x1a\n" +
	"\x16VERTEX_KIND_OCCURRENCE\x10\x03*t\n" +
	"\bEdgeKind\x12\x19\n" +
	"\x15EDGE_KIND_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11EDGE_KIND_DEFINES\x10\x01\x12\x16\n" +
	"\x12EDGE_KIND_CONTAINS\x10\x02\x12\x1e\n" +
	"\x1aEDGE_KIND_REFERENCES_LOCAL\x10\x03B\xbe\x01\n" +
	"\x12com.codiq.facts.v1B\n" +
	"FactsProtoP\x01ZBgithub.com/gaarutyunov/codiq/artifact/proto/codiq/facts/v1;factsv1\xa2\x02\x03CFX\xaa\x02\x0eCodiq.Facts.V1\xca\x02\x0eCodiq\\Facts\\V1\xe2\x02\x1aCodiq\\Facts\\V1\\GPBMetadata\xea\x02\x10Codiq::Facts::V1b\x06proto3"

var (
	file_codiq_facts_v1_facts_proto_rawDescOnce sync.Once
	file_codiq_facts_v1_facts_proto_rawDescData []byte
)

func file_codiq_facts_v1_facts_proto_rawDescGZIP() []byte {
	file_codiq_facts_v1_facts_proto_rawDescOnce.Do(func() {
		file_codiq_facts_v1_facts_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_codiq_facts_v1_facts_proto_rawDesc), len(file_codiq_facts_v1_facts_proto_rawDesc)))
	})
	return file_codiq_facts_v1_facts_proto_rawDescData
}

var file_codiq_facts_v1_facts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_codiq_facts_v1_facts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_codiq_facts_v1_facts_proto_goTypes = []any{
	(VertexKind)(0),    // 0: codiq.facts.v1.VertexKind
	(EdgeKind)(0),      // 1: codiq.facts.v1.EdgeKind
	(*Coord)(nil),      // 2: codiq.facts.v1.Coord
	(*Descriptor)(nil), // 3: codiq.facts.v1.Descriptor
	(*Ref)(nil),        // 4: codiq.facts.v1.Ref
	(*Edge)(nil),       // 5: codiq.facts.v1.Edge
	(*File)(nil),       // 6: codiq.facts.v1.File
	(*Scope)(nil),      // 7: codiq.facts.v1.Scope
	(*Occurrence)(nil), // 8: codiq.facts.v1.Occurrence
	(*FileFacts)(nil),  // 9: codiq.facts.v1.FileFacts
}
var file_codiq_facts_v1_facts_proto_depIdxs = []int32{
	2,  // 0: codiq.facts.v1.Descriptor.prefix:type_name -> codiq.facts.v1.Coord
	0,  // 1: codiq.facts.v1.Ref.vertex:type_name -> codiq.facts.v1.VertexKind
	1,  // 2: codiq.facts.v1.Edge.kind:type_name -> codiq.facts.v1.EdgeKind
	4,  // 3: codiq.facts.v1.Edge.source:type_name -> codiq.facts.v1.Ref
	4,  // 4: codiq.facts.v1.Edge.target:type_name -> codiq.facts.v1.Ref
	2,  // 5: codiq.facts.v1.File.coord:type_name -> codiq.facts.v1.Coord
	3,  // 6: codiq.facts.v1.Occurrence.descriptor:type_name -> codiq.facts.v1.Descriptor
	6,  // 7: codiq.facts.v1.FileFacts.file:type_name -> codiq.facts.v1.File
	7,  // 8: codiq.facts.v1.FileFacts.scopes:type_name -> codiq.facts.v1.Scope
	8,  // 9: codiq.facts.v1.FileFacts.occurrences:type_name -> codiq.facts.v1.Occurrence
	5,  // 10: codiq.facts.v1.FileFacts.edges:type_name -> codiq.facts.v1.Edge
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_codiq_facts_v1_facts_proto_init() }
func file_codiq_facts_v1_facts_proto_init() {
	if File_codiq_facts_v1_facts_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_codiq_facts_v1_facts_proto_rawDesc), len(file_codiq_facts_v1_facts_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codiq_facts_v1_facts_proto_goTypes,
		DependencyIndexes: file_codiq_facts_v1_facts_proto_depIdxs,
		EnumInfos:         file_codiq_facts_v1_facts_proto_enumTypes,
		MessageInfos:      file_codiq_facts_v1_facts_proto_msgTypes,
	}.Build()
	File_codiq_facts_v1_facts_proto = out.File
	file_codiq_facts_v1_facts_proto_goTypes = nil
	file_codiq_facts_v1_facts_proto_depIdxs = nil
}
