// Code generated by artifact/protogen from schema/codiq.graphql. DO NOT EDIT.
//
// One file's extracted facts (SPEC.md §5): the map phase's output, written to
// the shared volume (§10) and read back by the reduce (§6). The message shapes
// are the SDL's vertex tables; the identity model is the extractor's, so a row
// is named by a file-local ordinal rather than by the uuid the store assigns.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: codiq/facts/v1/facts.proto

package factsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// VertexKind names one of the SDL's vertex tables: which table an edge
// endpoint is a row in.
type VertexKind int32

const (
	VertexKind_VERTEX_KIND_UNSPECIFIED VertexKind = 0
	VertexKind_VERTEX_KIND_FILE        VertexKind = 1
	VertexKind_VERTEX_KIND_SCOPE       VertexKind = 2
	VertexKind_VERTEX_KIND_OCCURRENCE  VertexKind = 3
)

// Enum value maps for VertexKind.
var (
	VertexKind_name = map[int32]string{
		0: "VERTEX_KIND_UNSPECIFIED",
		1: "VERTEX_KIND_FILE",
		2: "VERTEX_KIND_SCOPE",
		3: "VERTEX_KIND_OCCURRENCE",
	}
	VertexKind_value = map[string]int32{
		"VERTEX_KIND_UNSPECIFIED": 0,
		"VERTEX_KIND_FILE":        1,
		"VERTEX_KIND_SCOPE":       2,
		"VERTEX_KIND_OCCURRENCE":  3,
	}
)

func (x VertexKind) Enum() *VertexKind {
	p := new(VertexKind)
	*p = x
	return p
}

func (x VertexKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VertexKind) Descriptor() protoreflect.EnumDescriptor {
	return file_codiq_facts_v1_facts_proto_enumTypes[0].Descriptor()
}

func (VertexKind) Type() protoreflect.EnumType {
	return &file_codiq_facts_v1_facts_proto_enumTypes[0]
}

func (x VertexKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VertexKind.Descriptor instead.
func (VertexKind) EnumDescriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{0}
}

// EdgeKind names an extracted, intra-file edge — SPEC.md §4.4's base edge
// tables. The derived cross-file kinds are the link pass's (§7) and never
// appear in an artifact.
type EdgeKind int32

const (
	EdgeKind_EDGE_KIND_UNSPECIFIED      EdgeKind = 0
	EdgeKind_EDGE_KIND_DEFINES          EdgeKind = 1
	EdgeKind_EDGE_KIND_CONTAINS         EdgeKind = 2
	EdgeKind_EDGE_KIND_REFERENCES_LOCAL EdgeKind = 3
)

// Enum value maps for EdgeKind.
var (
	EdgeKind_name = map[int32]string{
		0: "EDGE_KIND_UNSPECIFIED",
		1: "EDGE_KIND_DEFINES",
		2: "EDGE_KIND_CONTAINS",
		3: "EDGE_KIND_REFERENCES_LOCAL",
	}
	EdgeKind_value = map[string]int32{
		"EDGE_KIND_UNSPECIFIED":      0,
		"EDGE_KIND_DEFINES":          1,
		"EDGE_KIND_CONTAINS":         2,
		"EDGE_KIND_REFERENCES_LOCAL": 3,
	}
)

func (x EdgeKind) Enum() *EdgeKind {
	p := new(EdgeKind)
	*p = x
	return p
}

func (x EdgeKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeKind) Descriptor() protoreflect.EnumDescriptor {
	return file_codiq_facts_v1_facts_proto_enumTypes[1].Descriptor()
}

func (EdgeKind) Type() protoreflect.EnumType {
	return &file_codiq_facts_v1_facts_proto_enumTypes[1]
}

func (x EdgeKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeKind.Descriptor instead.
func (EdgeKind) EnumDescriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{1}
}

// Coord is a package coordinate: the descriptor prefix (SPEC.md §4.3) the
// batch resolves from a manifest and hands to every stanza. Its four
// components are the `file` row's pkg_* columns.
//
// coord.Coord's Root is deliberately absent. Root is extraction-time
// resolution state — it is what Coord.Namespace resolves a file path
// against — and by the time an artifact exists every namespace has already
// been resolved into a descriptor suffix. The descriptor prefix is exactly
// the four components below.
type Coord struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme  string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Manager string `protobuf:"bytes,2,opt,name=manager,proto3" json:"manager,omitempty"`
	Name    string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *Coord) Reset() {
	*x = Coord{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Coord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Coord) ProtoMessage() {}

func (x *Coord) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Coord.ProtoReflect.Descriptor instead.
func (*Coord) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{0}
}

func (x *Coord) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *Coord) GetManager() string {
	if x != nil {
		return x.Manager
	}
	return ""
}

func (x *Coord) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Coord) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Descriptor is a symbol's SCIP-style name (SPEC.md §4.3) as an artifact
// carries it: the two halves that produce it, not the joined string the
// `occurrence.descriptor` column holds. The split is §4.3's ownership
// boundary — prefix is the batch's, suffix is the stanza's — and an artifact
// is written before anything joins them.
type Descriptor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prefix *Coord `protobuf:"bytes,1,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Suffix string `protobuf:"bytes,2,opt,name=suffix,proto3" json:"suffix,omitempty"`
}

func (x *Descriptor) Reset() {
	*x = Descriptor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Descriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Descriptor) ProtoMessage() {}

func (x *Descriptor) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Descriptor.ProtoReflect.Descriptor instead.
func (*Descriptor) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{1}
}

func (x *Descriptor) GetPrefix() *Coord {
	if x != nil {
		return x.Prefix
	}
	return nil
}

func (x *Descriptor) GetSuffix() string {
	if x != nil {
		return x.Suffix
	}
	return ""
}

// Ref is an edge endpoint: which vertex table, and which row in it.
// `contains` is one label over two physical tables, so the endpoint's table
// is carried rather than inferred from the kind.
type Ref struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Vertex  VertexKind `protobuf:"varint,1,opt,name=vertex,proto3,enum=codiq.facts.v1.VertexKind" json:"vertex,omitempty"`
	LocalId int32      `protobuf:"varint,2,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
}

func (x *Ref) Reset() {
	*x = Ref{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ref) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ref) ProtoMessage() {}

func (x *Ref) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ref.ProtoReflect.Descriptor instead.
func (*Ref) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{2}
}

func (x *Ref) GetVertex() VertexKind {
	if x != nil {
		return x.Vertex
	}
	return VertexKind_VERTEX_KIND_UNSPECIFIED
}

func (x *Ref) GetLocalId() int32 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

// Edge is a row in one of the extracted edge tables. Both endpoints are in
// this file, always: an edge that leaves the file is the link pass's.
type Edge struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   EdgeKind `protobuf:"varint,1,opt,name=kind,proto3,enum=codiq.facts.v1.EdgeKind" json:"kind,omitempty"`
	Source *Ref     `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Target *Ref     `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
}

func (x *Edge) Reset() {
	*x = Edge{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Edge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Edge) ProtoMessage() {}

func (x *Edge) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Edge.ProtoReflect.Descriptor instead.
func (*Edge) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{3}
}

func (x *Edge) GetKind() EdgeKind {
	if x != nil {
		return x.Kind
	}
	return EdgeKind_EDGE_KIND_UNSPECIFIED
}

func (x *Edge) GetSource() *Ref {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *Edge) GetTarget() *Ref {
	if x != nil {
		return x.Target
	}
	return nil
}

// File is a row in `file`, as the extractor produces it.
type File struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Lang string `protobuf:"bytes,2,opt,name=lang,proto3" json:"lang,omitempty"`
	// The pkg_* columns, as the coordinate they are.
	Coord  *Coord `protobuf:"bytes,3,opt,name=coord,proto3" json:"coord,omitempty"`
	Corpus string `protobuf:"bytes,4,opt,name=corpus,proto3" json:"corpus,omitempty"`
}

func (x *File) Reset() {
	*x = File{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{4}
}

func (x *File) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *File) GetLang() string {
	if x != nil {
		return x.Lang
	}
	return ""
}

func (x *File) GetCoord() *Coord {
	if x != nil {
		return x.Coord
	}
	return nil
}

func (x *File) GetCorpus() string {
	if x != nil {
		return x.Corpus
	}
	return ""
}

// Scope is a row in `scope`, as the extractor produces it.
type Scope struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identity inside this artifact: a facts.LocalID, not the uuid
	// the store assigns at insert. Numbered from 1; 0 means none.
	LocalId    int32  `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	Kind       string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	RangeStart int32  `protobuf:"varint,3,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd   int32  `protobuf:"varint,4,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// An intra-file reference to another row's local_id; 0 means none.
	ParentScopeId int32 `protobuf:"varint,5,opt,name=parent_scope_id,json=parentScopeId,proto3" json:"parent_scope_id,omitempty"`
}

func (x *Scope) Reset() {
	*x = Scope{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Scope) ProtoMessage() {}

func (x *Scope) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Scope.ProtoReflect.Descriptor instead.
func (*Scope) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{5}
}

func (x *Scope) GetLocalId() int32 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Scope) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Scope) GetRangeStart() int32 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *Scope) GetRangeEnd() int32 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

func (x *Scope) GetParentScopeId() int32 {
	if x != nil {
		return x.ParentScopeId
	}
	return 0
}

// Occurrence is a row in `occurrence`, as the extractor produces it.
type Occurrence struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Identity inside this artifact: a facts.LocalID, not the uuid
	// the store assigns at insert. Numbered from 1; 0 means none.
	LocalId     int32       `protobuf:"varint,1,opt,name=local_id,json=localId,proto3" json:"local_id,omitempty"`
	Descriptor_ *Descriptor `protobuf:"bytes,2,opt,name=descriptor,proto3" json:"descriptor,omitempty"`
	Role        string      `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	SymbolKind  string      `protobuf:"bytes,4,opt,name=symbol_kind,json=symbolKind,proto3" json:"symbol_kind,omitempty"`
	Name        string      `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	RangeStart  int32       `protobuf:"varint,6,opt,name=range_start,json=rangeStart,proto3" json:"range_start,omitempty"`
	RangeEnd    int32       `protobuf:"varint,7,opt,name=range_end,json=rangeEnd,proto3" json:"range_end,omitempty"`
	// An intra-file reference to another row's local_id; 0 means none.
	ScopeId int32 `protobuf:"varint,8,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
}

func (x *Occurrence) Reset() {
	*x = Occurrence{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Occurrence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Occurrence) ProtoMessage() {}

func (x *Occurrence) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Occurrence.ProtoReflect.Descriptor instead.
func (*Occurrence) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{6}
}

func (x *Occurrence) GetLocalId() int32 {
	if x != nil {
		return x.LocalId
	}
	return 0
}

func (x *Occurrence) GetDescriptor_() *Descriptor {
	if x != nil {
		return x.Descriptor_
	}
	return nil
}

func (x *Occurrence) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *Occurrence) GetSymbolKind() string {
	if x != nil {
		return x.SymbolKind
	}
	return ""
}

func (x *Occurrence) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Occurrence) GetRangeStart() int32 {
	if x != nil {
		return x.RangeStart
	}
	return 0
}

func (x *Occurrence) GetRangeEnd() int32 {
	if x != nil {
		return x.RangeEnd
	}
	return 0
}

func (x *Occurrence) GetScopeId() int32 {
	if x != nil {
		return x.ScopeId
	}
	return 0
}

// FileFacts is everything extraction knows about one file: the unit the map
// phase writes to the shared volume and the reduce phase loads (SPEC.md §5,
// §6). It is wholly self-contained — nothing in it refers to another file.
type FileFacts struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	File        *File         `protobuf:"bytes,1,opt,name=file,proto3" json:"file,omitempty"`
	Scopes      []*Scope      `protobuf:"bytes,2,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Occurrences []*Occurrence `protobuf:"bytes,3,rep,name=occurrences,proto3" json:"occurrences,omitempty"`
	Edges       []*Edge       `protobuf:"bytes,4,rep,name=edges,proto3" json:"edges,omitempty"`
	// Non-empty when the file could not be parsed (SPEC.md §5's poison file).
	// The Parser contract returns no error, so the failure travels with the
	// facts: the row lists are empty and the caller decides what to do.
	ParseError string `protobuf:"bytes,5,opt,name=parse_error,json=parseError,proto3" json:"parse_error,omitempty"`
}

func (x *FileFacts) Reset() {
	*x = FileFacts{}
	if protoimpl.UnsafeEnabled {
		mi := &file_codiq_facts_v1_facts_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FileFacts) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileFacts) ProtoMessage() {}

func (x *FileFacts) ProtoReflect() protoreflect.Message {
	mi := &file_codiq_facts_v1_facts_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileFacts.ProtoReflect.Descriptor instead.
func (*FileFacts) Descriptor() ([]byte, []int) {
	return file_codiq_facts_v1_facts_proto_rawDescGZIP(), []int{7}
}

func (x *FileFacts) GetFile() *File {
	if x != nil {
		return x.File
	}
	return nil
}

func (x *FileFacts) GetScopes() []*Scope {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *FileFacts) GetOccurrences() []*Occurrence {
	if x != nil {
		return x.Occurrences
	}
	return nil
}

func (x *FileFacts) GetEdges() []*Edge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *FileFacts) GetParseError() string {
	if x != nil {
		return x.ParseError
	}
	return ""
}

var File_codiq_facts_v1_facts_proto protoreflect.FileDescriptor

var file_codiq_facts_v1_facts_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x76, 0x31,
	0x2f, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x63, 0x6f,
	0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x67, 0x0a, 0x05,
	0x43, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x61, 0x6e, 0x61, 0x67, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x53, 0x0a, 0x0a, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x6f, 0x72, 0x12, 0x2d, 0x0a, 0x06, 0x70, 0x72, 0x65, 0x66, 0x69, 0x78, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x06, 0x70, 0x72, 0x65, 0x66,
	0x69, 0x78, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x75, 0x66, 0x66, 0x69, 0x78, 0x22, 0x54, 0x0a, 0x03, 0x52, 0x65,
	0x66, 0x12, 0x32, 0x0a, 0x06, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0e, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x06, 0x76,
	0x65, 0x72, 0x74, 0x65, 0x78, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64,
	0x22, 0x8e, 0x01, 0x0a, 0x04, 0x45, 0x64, 0x67, 0x65, 0x12, 0x2c, 0x0a, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x4b, 0x69, 0x6e,
	0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x2b, 0x0a, 0x06, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e,
	0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x2b, 0x0a, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63,
	0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x65, 0x66, 0x52, 0x06, 0x74, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x22, 0x73, 0x0a, 0x04, 0x46, 0x69, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x74,
	0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a,
	0x04, 0x6c, 0x61, 0x6e, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c, 0x61, 0x6e,
	0x67, 0x12, 0x2b, 0x0a, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x15, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x43, 0x6f, 0x6f, 0x72, 0x64, 0x52, 0x05, 0x63, 0x6f, 0x6f, 0x72, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x63, 0x6f, 0x72, 0x70, 0x75, 0x73, 0x22, 0x9c, 0x01, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x70, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x65, 0x6e, 0x64, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x45, 0x6e, 0x64, 0x12, 0x26, 0x0a,
	0x0f, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x53, 0x63,
	0x6f, 0x70, 0x65, 0x49, 0x64, 0x22, 0x85, 0x02, 0x0a, 0x0a, 0x4f, 0x63, 0x63, 0x75, 0x72, 0x72,
	0x65, 0x6e, 0x63, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x49, 0x64, 0x12,
	0x3a, 0x0a, 0x0a, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63, 0x74,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x52,
	0x0a, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x72,
	0x6f, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x6f, 0x6c, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x5f, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x79, 0x6d, 0x62, 0x6f, 0x6c, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x67, 0x65,
	0x53, 0x74, 0x61, 0x72, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x65,
	0x6e, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x72, 0x61, 0x6e, 0x67, 0x65, 0x45,
	0x6e, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x49, 0x64, 0x22, 0xef, 0x01,
	0x0a, 0x09, 0x46, 0x69, 0x6c, 0x65, 0x46, 0x61, 0x63, 0x74, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x66,
	0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x64, 0x69,
	0x71, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x69, 0x6c, 0x65, 0x52,
	0x04, 0x66, 0x69, 0x6c, 0x65, 0x12, 0x2d, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61,
	0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x63, 0x6f, 0x70, 0x65, 0x52, 0x06, 0x73, 0x63,
	0x6f, 0x70, 0x65, 0x73, 0x12, 0x3c, 0x0a, 0x0b, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e,
	0x63, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x63, 0x6f, 0x64, 0x69,
	0x71, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4f, 0x63, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0b, 0x6f, 0x63, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x63,
	0x65, 0x73, 0x12, 0x2a, 0x0a, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x45, 0x64, 0x67, 0x65, 0x52, 0x05, 0x65, 0x64, 0x67, 0x65, 0x73, 0x12, 0x1f,
	0x0a, 0x0b, 0x70, 0x61, 0x72, 0x73, 0x65, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x61, 0x72, 0x73, 0x65, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x2a,
	0x72, 0x0a, 0x0a, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x1b, 0x0a,
	0x17, 0x56, 0x45, 0x52, 0x54, 0x45, 0x58, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x14, 0x0a, 0x10, 0x56, 0x45,
	0x52, 0x54, 0x45, 0x58, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x46, 0x49, 0x4c, 0x45, 0x10, 0x01,
	0x12, 0x15, 0x0a, 0x11, 0x56, 0x45, 0x52, 0x54, 0x45, 0x58, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f,
	0x53, 0x43, 0x4f, 0x50, 0x45, 0x10, 0x02, 0x12, 0x1a, 0x0a, 0x16, 0x56, 0x45, 0x52, 0x54, 0x45,
	0x58, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x4f, 0x43, 0x43, 0x55, 0x52, 0x52, 0x45, 0x4e, 0x43,
	0x45, 0x10, 0x03, 0x2a, 0x74, 0x0a, 0x08, 0x45, 0x64, 0x67, 0x65, 0x4b, 0x69, 0x6e, 0x64, 0x12,
	0x19, 0x0a, 0x15, 0x45, 0x44, 0x47, 0x45, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x55, 0x4e, 0x53,
	0x50, 0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x15, 0x0a, 0x11, 0x45, 0x44,
	0x47, 0x45, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x44, 0x45, 0x46, 0x49, 0x4e, 0x45, 0x53, 0x10,
	0x01, 0x12, 0x16, 0x0a, 0x12, 0x45, 0x44, 0x47, 0x45, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x43,
	0x4f, 0x4e, 0x54, 0x41, 0x49, 0x4e, 0x53, 0x10, 0x02, 0x12, 0x1e, 0x0a, 0x1a, 0x45, 0x44, 0x47,
	0x45, 0x5f, 0x4b, 0x49, 0x4e, 0x44, 0x5f, 0x52, 0x45, 0x46, 0x45, 0x52, 0x45, 0x4e, 0x43, 0x45,
	0x53, 0x5f, 0x4c, 0x4f, 0x43, 0x41, 0x4c, 0x10, 0x03, 0x42, 0xbe, 0x01, 0x0a, 0x12, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2e, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x76, 0x31,
	0x42, 0x0a, 0x46, 0x61, 0x63, 0x74, 0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x42,
	0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x61, 0x61, 0x72, 0x75,
	0x74, 0x79, 0x75, 0x6e, 0x6f, 0x76, 0x2f, 0x63, 0x6f, 0x64, 0x69, 0x71, 0x2f, 0x61, 0x72, 0x74,
	0x69, 0x66, 0x61, 0x63, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6f, 0x64, 0x69,
	0x71, 0x2f, 0x66, 0x61, 0x63, 0x74, 0x73, 0x2f, 0x76, 0x31, 0x3b, 0x66, 0x61, 0x63, 0x74, 0x73,
	0x76, 0x31, 0xa2, 0x02, 0x03, 0x43, 0x46, 0x58, 0xaa, 0x02, 0x0e, 0x43, 0x6f, 0x64, 0x69, 0x71,
	0x2e, 0x46, 0x61, 0x63, 0x74, 0x73, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x0e, 0x43, 0x6f, 0x64, 0x69,
	0x71, 0x5c, 0x46, 0x61, 0x63, 0x74, 0x73, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x1a, 0x43, 0x6f, 0x64,
	0x69, 0x71, 0x5c, 0x46, 0x61, 0x63, 0x74, 0x73, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x10, 0x43, 0x6f, 0x64, 0x69, 0x71, 0x3a,
	0x3a, 0x46, 0x61, 0x63, 0x74, 0x73, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_codiq_facts_v1_facts_proto_rawDescOnce sync.Once
	file_codiq_facts_v1_facts_proto_rawDescData = file_codiq_facts_v1_facts_proto_rawDesc
)

func file_codiq_facts_v1_facts_proto_rawDescGZIP() []byte {
	file_codiq_facts_v1_facts_proto_rawDescOnce.Do(func() {
		file_codiq_facts_v1_facts_proto_rawDescData = protoimpl.X.CompressGZIP(file_codiq_facts_v1_facts_proto_rawDescData)
	})
	return file_codiq_facts_v1_facts_proto_rawDescData
}

var file_codiq_facts_v1_facts_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_codiq_facts_v1_facts_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_codiq_facts_v1_facts_proto_goTypes = []interface{}{
	(VertexKind)(0),    // 0: codiq.facts.v1.VertexKind
	(EdgeKind)(0),      // 1: codiq.facts.v1.EdgeKind
	(*Coord)(nil),      // 2: codiq.facts.v1.Coord
	(*Descriptor)(nil), // 3: codiq.facts.v1.Descriptor
	(*Ref)(nil),        // 4: codiq.facts.v1.Ref
	(*Edge)(nil),       // 5: codiq.facts.v1.Edge
	(*File)(nil),       // 6: codiq.facts.v1.File
	(*Scope)(nil),      // 7: codiq.facts.v1.Scope
	(*Occurrence)(nil), // 8: codiq.facts.v1.Occurrence
	(*FileFacts)(nil),  // 9: codiq.facts.v1.FileFacts
}
var file_codiq_facts_v1_facts_proto_depIdxs = []int32{
	2,  // 0: codiq.facts.v1.Descriptor.prefix:type_name -> codiq.facts.v1.Coord
	0,  // 1: codiq.facts.v1.Ref.vertex:type_name -> codiq.facts.v1.VertexKind
	1,  // 2: codiq.facts.v1.Edge.kind:type_name -> codiq.facts.v1.EdgeKind
	4,  // 3: codiq.facts.v1.Edge.source:type_name -> codiq.facts.v1.Ref
	4,  // 4: codiq.facts.v1.Edge.target:type_name -> codiq.facts.v1.Ref
	2,  // 5: codiq.facts.v1.File.coord:type_name -> codiq.facts.v1.Coord
	3,  // 6: codiq.facts.v1.Occurrence.descriptor:type_name -> codiq.facts.v1.Descriptor
	6,  // 7: codiq.facts.v1.FileFacts.file:type_name -> codiq.facts.v1.File
	7,  // 8: codiq.facts.v1.FileFacts.scopes:type_name -> codiq.facts.v1.Scope
	8,  // 9: codiq.facts.v1.FileFacts.occurrences:type_name -> codiq.facts.v1.Occurrence
	5,  // 10: codiq.facts.v1.FileFacts.edges:type_name -> codiq.facts.v1.Edge
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_codiq_facts_v1_facts_proto_init() }
func file_codiq_facts_v1_facts_proto_init() {
	if File_codiq_facts_v1_facts_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_codiq_facts_v1_facts_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Coord); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_codiq_facts_v1_facts_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Descriptor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_codiq_facts_v1_facts_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ref); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_codiq_facts_v1_facts_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Edge); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_codiq_facts_v1_facts_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*File); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_codiq_facts_v1_facts_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Scope); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_codiq_facts_v1_facts_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Occurrence); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_codiq_facts_v1_facts_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FileFacts); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_codiq_facts_v1_facts_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_codiq_facts_v1_facts_proto_goTypes,
		DependencyIndexes: file_codiq_facts_v1_facts_proto_depIdxs,
		EnumInfos:         file_codiq_facts_v1_facts_proto_enumTypes,
		MessageInfos:      file_codiq_facts_v1_facts_proto_msgTypes,
	}.Build()
	File_codiq_facts_v1_facts_proto = out.File
	file_codiq_facts_v1_facts_proto_rawDesc = nil
	file_codiq_facts_v1_facts_proto_goTypes = nil
	file_codiq_facts_v1_facts_proto_depIdxs = nil
}
