// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package sqlc

import (
	"context"
)

// iteratorForCopyContainsOccurrence implements pgx.CopyFromSource.
type iteratorForCopyContainsOccurrence struct {
	rows                 []CopyContainsOccurrenceParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyContainsOccurrence) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyContainsOccurrence) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SourceID,
		r.rows[0].TargetID,
	}, nil
}

func (r iteratorForCopyContainsOccurrence) Err() error {
	return nil
}

func (q *Queries) CopyContainsOccurrence(ctx context.Context, arg []CopyContainsOccurrenceParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"contains_occurrence"}, []string{"source_id", "target_id"}, &iteratorForCopyContainsOccurrence{rows: arg})
}

// iteratorForCopyContainsScope implements pgx.CopyFromSource.
type iteratorForCopyContainsScope struct {
	rows                 []CopyContainsScopeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyContainsScope) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyContainsScope) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SourceID,
		r.rows[0].TargetID,
	}, nil
}

func (r iteratorForCopyContainsScope) Err() error {
	return nil
}

func (q *Queries) CopyContainsScope(ctx context.Context, arg []CopyContainsScopeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"contains_scope"}, []string{"source_id", "target_id"}, &iteratorForCopyContainsScope{rows: arg})
}

// iteratorForCopyDefines implements pgx.CopyFromSource.
type iteratorForCopyDefines struct {
	rows                 []CopyDefinesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyDefines) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyDefines) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SourceID,
		r.rows[0].TargetID,
	}, nil
}

func (r iteratorForCopyDefines) Err() error {
	return nil
}

func (q *Queries) CopyDefines(ctx context.Context, arg []CopyDefinesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"defines"}, []string{"source_id", "target_id"}, &iteratorForCopyDefines{rows: arg})
}

// iteratorForCopyOccurrences implements pgx.CopyFromSource.
type iteratorForCopyOccurrences struct {
	rows                 []CopyOccurrencesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyOccurrences) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyOccurrences) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].FileID,
		r.rows[0].Descriptor,
		r.rows[0].Role,
		r.rows[0].SymbolKind,
		r.rows[0].Name,
		r.rows[0].RangeStart,
		r.rows[0].RangeEnd,
		r.rows[0].ScopeID,
	}, nil
}

func (r iteratorForCopyOccurrences) Err() error {
	return nil
}

func (q *Queries) CopyOccurrences(ctx context.Context, arg []CopyOccurrencesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"occurrence"}, []string{"id", "file_id", "descriptor", "role", "symbol_kind", "name", "range_start", "range_end", "scope_id"}, &iteratorForCopyOccurrences{rows: arg})
}

// iteratorForCopyReferencesLocal implements pgx.CopyFromSource.
type iteratorForCopyReferencesLocal struct {
	rows                 []CopyReferencesLocalParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyReferencesLocal) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyReferencesLocal) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SourceID,
		r.rows[0].TargetID,
	}, nil
}

func (r iteratorForCopyReferencesLocal) Err() error {
	return nil
}

func (q *Queries) CopyReferencesLocal(ctx context.Context, arg []CopyReferencesLocalParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"references_local"}, []string{"source_id", "target_id"}, &iteratorForCopyReferencesLocal{rows: arg})
}

// iteratorForCopyScopes implements pgx.CopyFromSource.
type iteratorForCopyScopes struct {
	rows                 []CopyScopesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCopyScopes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCopyScopes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ID,
		r.rows[0].FileID,
		r.rows[0].Kind,
		r.rows[0].RangeStart,
		r.rows[0].RangeEnd,
		r.rows[0].ParentScopeID,
	}, nil
}

func (r iteratorForCopyScopes) Err() error {
	return nil
}

// ===========================================================================
// Bulk insert (SPEC.md §6: `CopyFrom` straight into the target tables; no
// staging, no merge, no ON CONFLICT -- delete-first guarantees no collision)
// ===========================================================================
func (q *Queries) CopyScopes(ctx context.Context, arg []CopyScopesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"scope"}, []string{"id", "file_id", "kind", "range_start", "range_end", "parent_scope_id"}, &iteratorForCopyScopes{rows: arg})
}
