// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"github.com/google/uuid"
)

type Call struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type ContainsOccurrence struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type ContainsScope struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type Define struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type File struct {
	ID         uuid.UUID
	Path       string
	Lang       string
	PkgScheme  string
	PkgManager string
	PkgName    string
	PkgVersion string
	Corpus     string
}

type Implement struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type Import struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type Occurrence struct {
	ID         uuid.UUID
	FileID     uuid.UUID
	Descriptor string
	Role       string
	SymbolKind string
	Name       string
	RangeStart int32
	RangeEnd   int32
	ScopeID    *uuid.UUID
}

type ReferencesLocal struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type ResolvesTo struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}

type Scope struct {
	ID            uuid.UUID
	FileID        uuid.UUID
	Kind          string
	RangeStart    int32
	RangeEnd      int32
	ParentScopeID *uuid.UUID
}

type TypeDefine struct {
	SourceID uuid.UUID
	TargetID uuid.UUID
}
